In [13]:
#1 q
'''A Python library is a comprehensive set of functions and methods designed to enable users to accomplish diverse tasks without the need to develop the functionality from the ground up. Python libraries are instrumental in saving time and effort, as they offer pre-written code that addresses common challenges or tasks. By tapping into these libraries, users can easily access proven solutions, streamlining the development process and enhancing overall efficiency.'''

'A Python library is a comprehensive set of functions and methods designed to enable users to accomplish diverse tasks without the need to develop the functionality from the ground up. Python libraries are instrumental in saving time and effort, as they offer pre-written code that addresses common challenges or tasks. By tapping into these libraries, users can easily access proven solutions, streamlining the development process and enhancing overall efficiency.'

In [15]:
# 2Q

'''The primary distinctions between a NumPy array and a list include the following:

Homogeneity and Size:

NumPy arrays are homogeneous, meaning all elements must be of the same data type. Additionally, the size of a NumPy array is fixed upon creation.
Lists, on the other hand, can contain elements of different data types, and their size can be dynamically adjusted during runtime.
Performance:

NumPy arrays are designed for numerical operations and provide better performance, especially for large datasets, compared to lists. This is due to optimized implementations of array operations that take advantage of low-level optimizations.
Lists may not perform as well as NumPy arrays for numerical computations, particularly when dealing with extensive datasets.
Vectorized Operations:

NumPy arrays support vectorized operations, allowing mathematical operations to be applied element-wise without the need for explicit looping. This capability significantly enhances the efficiency of numerical computations.
Lists require explicit iteration for similar operations, making them less efficient for mathematical computations involving large datasets.
In summary, while NumPy arrays are homogeneous, have a fixed size, and offer optimized performance for numerical operations, lists are more flexible in terms of data types and size. The choice between NumPy arrays and lists depends on the specific requirements of the task at hand, with NumPy arrays being particularly well-suited for numerical computations and scientific computing.'''

'The primary distinctions between a NumPy array and a list include the following:\n\nHomogeneity and Size:\n\nNumPy arrays are homogeneous, meaning all elements must be of the same data type. Additionally, the size of a NumPy array is fixed upon creation.\nLists, on the other hand, can contain elements of different data types, and their size can be dynamically adjusted during runtime.\nPerformance:\n\nNumPy arrays are designed for numerical operations and provide better performance, especially for large datasets, compared to lists. This is due to optimized implementations of array operations that take advantage of low-level optimizations.\nLists may not perform as well as NumPy arrays for numerical computations, particularly when dealing with extensive datasets.\nVectorized Operations:\n\nNumPy arrays support vectorized operations, allowing mathematical operations to be applied element-wise without the need for explicit looping. This capability significantly enhances the efficiency of 

In [16]:
# 3 Q
'''The shape, size, and dimension of the given array are:
Shape: (3, 4) Size: 12 (total number of elements) Dimension: 2 (2D array)'''

'The shape, size, and dimension of the given array are:\nShape: (3, 4) Size: 12 (total number of elements) Dimension: 2 (2D array)'

In [1]:
#4th q
array = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
first_row = array[0]
print(first_row)

[1, 2, 3, 4]


In [2]:
# 5
array = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
element = array[2][3]
print(element)

12


In [3]:
# 6
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
odd_elements = array[:, 1::2]
print(odd_elements)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [4]:
# 7
import numpy as np

random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.67959213 0.68111114 0.69278262]
 [0.58090319 0.96862822 0.11122946]
 [0.65281625 0.56982352 0.42286769]]


In [17]:
# 8th question
'''np.random.rand generates random numbers from a uniform distribution between 0 and 1, while np.random.randn generates random numbers from a standard normal distribution (mean 0 and standard deviation 1).'''

'np.random.rand generates random numbers from a uniform distribution between 0 and 1, while np.random.randn generates random numbers from a standard normal distribution (mean 0 and standard deviation 1).'

In [5]:
# 9
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
expanded_array = np.expand_dims(array, axis=0)
print(expanded_array.shape)

(1, 3, 4)


In [6]:
#10
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
transposed_array = np.transpose(array)
print(transposed_array)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [7]:
#11
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Index-wise multiplication
index_wise_mul = A * B

# Matrix multiplication
matrix_mul = np.matmul(A, B)

# Add both matrices
matrix_addition = A + B

# Subtract matrix B from A
matrix_subtraction = A - B

# Divide matrix B by A
matrix_division = B / A

print("Index-wise multiplication:\n", index_wise_mul)
print("Matrix multiplication:\n", matrix_mul)
print("Matrix addition:\n", matrix_addition)
print("Matrix subtraction:\n", matrix_subtraction)
print("Matrix division:\n", matrix_division)

Index-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Matrix addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Matrix division:
 [[9.         4.         2.33333333]
 [1.5        1.         0.66666667]
 [0.42857143 0.25       0.11111111]]


In [18]:
# 12 
# The function in NumPy used to swap the byte order of an array is np.ndarray.byteswap()

In [19]:
# 13
'''The np.linalg.inv function is used to calculate the inverse of a square matrix. It is significant in linear algebra for solving systems of linear equations and other matrix operations.'''

'The np.linalg.inv function is used to calculate the inverse of a square matrix. It is significant in linear algebra for solving systems of linear equations and other matrix operations.'

In [8]:
# 14 
# reshaped_array = np.reshape(original_array, new_shape)

# 15 q

In [14]:
'''Broadcasting in NumPy refers to the ability to perform arithmetic operations on arrays of different shapes. NumPy automatically broadcasts arrays to make them compatible for element-wise operations, allowing you to perform operations between arrays of different shapes without explicitly adding dimensions.'''

'Broadcasting in NumPy refers to the ability to perform arithmetic operations on arrays of different shapes. NumPy automatically broadcasts arrays to make them compatible for element-wise operations, allowing you to perform operations between arrays of different shapes without explicitly adding dimensions.'